
###+++--- GPGConf ---+++###
ldap-proxy ldap.basisit.de
###+++--- GPGConf ---+++### Mi 05 Mär 2025 14:24:38 CET
# GPGConf edited this configuration file.
# It will disable options before this marked block, but it will
# never change anything below these lines.
